import { bestInboxDeal } from "../sections/bestInboxDeal.js";
import { bestRatedExperience } from "../sections/bestRatedExperience.js";
import { carListings } from "../sections/carListings.js";
import { exploreByCity } from "../sections/exploreByCity.js";
import { footer } from "../sections/footer.js";
import { generalListings } from "../sections/generalListings.js";
import { header } from "../sections/header.js";
import { hero } from "../sections/hero.js";
import { ourLatestCategories } from "../sections/ourLatestCategories.js";
import { popularPlaces } from "../sections/popularPlaces.js";
import { realEstateListings } from "../sections/realEstateListings.js";
import { restaurantsListings } from "../sections/restaurantsListings.js";
import { tipsAndTricks } from "../sections/tipsAndTricks.js";
import { twoImageBlocks } from "../sections/twoImageBlocks.js";

header();
hero();
popularPlaces();
generalListings();
bestRatedExperience();
restaurantsListings();
ourLatestCategories();
twoImageBlocks();
realEstateListings();
exploreByCity();
carListings();
tipsAndTricks();
bestInboxDeal();
footer();