import { bestInboxDeal } from "../components/bestInboxDeal.js";
import { bestRatedExperience } from "../components/bestRatedExperience.js";
import { carListings } from "../components/carListings.js";
import { exploreByCity } from "../components/exploreByCity.js";
import { footer } from "../components/footer.js";
import { generalListings } from "../components/generalListings.js";
import { header } from "../components/header.js";
import { hero } from "../components/hero.js";
import { ourLatestCategories } from "../components/ourLatestCategories.js";
import { popularPlaces } from "../components/popularPlaces.js";
import { realEstateListings } from "../components/realEstateListings.js";
import { restaurantsListings } from "../components/restaurantsListings.js";
import { tipsAndTricks } from "../components/tipsAndTricks.js";
import { twoImageBlocks } from "../components/twoImageBlocks.js";

header();
hero();
popularPlaces();
generalListings();
bestRatedExperience();
restaurantsListings();
ourLatestCategories();
twoImageBlocks();
realEstateListings();
exploreByCity();
carListings();
tipsAndTricks();
bestInboxDeal();
footer();